export const ITEM_STATUS = {
  INGESTED: 'INGESTED',
  CLASSIFIED: 'CLASSIFIED',
  TITLED: 'TITLED',
  COVERED: 'COVERED',
  COMPLIANCE_PASS: 'COMPLIANCE_PASS',
  COMPLIANCE_FAIL: 'COMPLIANCE_FAIL',
  COMPLIANCE_REVIEW: 'COMPLIANCE_REVIEW',
  COMPLIANCE_HOLD: 'COMPLIANCE_HOLD',
  PUBLISHED: 'PUBLISHED',
  DISTRIBUTED: 'DISTRIBUTED',
} as const;

export type ItemStatus = (typeof ITEM_STATUS)[keyof typeof ITEM_STATUS];
